name: release

on:
  push:
    tags:
      - '*'

jobs:
  # push image to Docker Hub
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Terrascan Action
      uses: actions/checkout@v2

    - name: Build Terrascan Action docker image
      run: ./scripts/docker-build.sh

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Terrascan Action latest tag docker image
      run: ./scripts/docker-push-latest-tag.sh
